services:
  - type: web
    name: franklin-planner
    env: python
    build:
      pythonVersion: 3.12.4
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: planner-db
          property: connectionString
